-- INE Product Price Tracker — Supabase Database Schema

-- 1. Tracked Products Table
CREATE TABLE IF NOT EXISTS public.tracked_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER UNIQUE NOT NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  brand TEXT,
  category TEXT,
  sku TEXT,
  url TEXT NOT NULL,
  image_url TEXT,
  current_price NUMERIC(10,2),
  current_stock INTEGER,
  stock_status TEXT,
  initial_price NUMERIC(10,2),
  target_price NUMERIC(10,2),
  seller TEXT,
  rating NUMERIC(3,2),
  scrape_interval_hours INTEGER DEFAULT 2,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_scraped_at TIMESTAMPTZ,
  last_scrape_status TEXT
);

-- 2. Price History Table
CREATE TABLE IF NOT EXISTS public.price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER REFERENCES public.tracked_products(product_id) ON DELETE CASCADE,
  price NUMERIC(10,2) NOT NULL,
  stock INTEGER,
  stock_status TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Scrape Logs Table (Honest per-attempt log)
CREATE TABLE IF NOT EXISTS public.scrape_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER REFERENCES public.tracked_products(product_id) ON DELETE CASCADE,
  product_name TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  status TEXT NOT NULL CHECK (status IN ('success', 'retried', 'failed')),
  attempts_count INTEGER DEFAULT 1,
  response_time_ms INTEGER,
  price_found NUMERIC(10,2),
  stock_found INTEGER,
  error_message TEXT,
  strategy_used TEXT DEFAULT 'playwright_headed_simulation'
);

-- 4. In-App Alerts & Notifications Table
CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER REFERENCES public.tracked_products(product_id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('price_drop', 'back_in_stock', 'structure_change')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_price_history_product_time ON public.price_history(product_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_scrape_logs_product_time ON public.scrape_logs(product_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_read ON public.alerts(is_read, created_at DESC);

-- Row Level Security (RLS) Enablement
ALTER TABLE public.tracked_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scrape_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- Anonymous Access Policies for Public Demo
CREATE POLICY "Allow public read/write tracked_products" ON public.tracked_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write price_history" ON public.price_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write scrape_logs" ON public.scrape_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write alerts" ON public.alerts FOR ALL USING (true) WITH CHECK (true);
